// ========================================
// ALPHAFAMILY PRO - DATA MODULE
// ========================================

// Translations
const TRANS = {
    ru: {
        subtitle: "Учим буквы и цифры весело!",
        jun_t: "Малыши", jun_d: "до 6 лет", sen_t: "Старшие", sen_d: "до 10 лет",
        sel_sub: "Выбери предмет:", l_let: "Буквы", l_math: "Математика", l_syllables: "Слоги",
        map: "Карта уровней", dict: "Словарь", hard: "Сложно",
        p_let: "Буква", p_num: "Цифра", paint: "Раскрась!", pop: "Лопай!",
        write: "Напиши слово:", task: "Задания", table: "Таблица", choose: "Выбери цифру",
        yes: [
            "Молодец!", "Отлично!", "Супер!", "Великолепно!", "Ты умница!",
            "У тебя здорово получается!", "Невероятно!", "Потрясающе!", "Ты справился!",
            "Какой ты способный!", "Замечательно!", "Я горжусь тобой!",
            "Ты настоящий герой!", "Продолжай в том же духе!", "Ты становишься всё лучше!"
        ],
        no: [
            "Попробуй ещё раз, у тебя обязательно получится!", "Почти получилось! Давай ещё разок!",
            "Не переживай, попробуем снова!", "Всё хорошо, давай попробуем ещё!",
            "Ты молодец, что стараешься! Попробуй снова!", "В следующий раз точно получится!",
            "Ничего страшного! Давай вместе попробуем!", "Ошибаться — это нормально! Попробуй ещё!",
            "Не сдавайся, у тебя всё получится!", "Я верю в тебя! Попробуй ещё раз!"
        ], find: "Найди слова", find_p: "Найди:",
        syl_basic: "По слогам", syl_advanced: "Собери слово", next_word: "Следующее слово", reset: "Сброс",
        select_mode: "Выбери режим:", click_syllable: "Нажми на слог",
        select_lang: "Выбери язык:"
    },
    en: {
        subtitle: "Learn letters and numbers with fun!",
        jun_t: "Junior", jun_d: "up to 6", sen_t: "Senior", sen_d: "up to 10",
        sel_sub: "Select Subject:", l_let: "Letters", l_math: "Math",
        map: "Level Map", dict: "Dictionary", hard: "Hard",
        p_let: "Letter", p_num: "Number", paint: "Paint it!", pop: "Pop it!",
        write: "Write word:", task: "Tasks", table: "Table", choose: "Choose number",
        yes: [
            "Good job!", "Excellent!", "Super!", "Amazing!", "You're so smart!",
            "You're doing great!", "Incredible!", "Fantastic!", "You did it!",
            "You're a star!", "Wonderful!", "I'm proud of you!",
            "You're awesome!", "Keep it up!", "You're getting better!"
        ],
        no: [
            "Try again, you can do it!", "Almost there! One more time!",
            "Don't worry, let's try again!", "It's okay, let's give it another go!",
            "Good effort! Try once more!", "You'll get it next time!",
            "No problem! Let's try together!", "Mistakes help us learn! Try again!",
            "Don't give up, you've got this!", "I believe in you! Try again!"
        ], find: "Find Words", find_p: "Find:",
        select_lang: "Select Language:"
    },
    he: {
        subtitle: "לומדים אותיות ומספרים בכיף!",
        jun_t: "קטנטנים", jun_d: "עד גיל 6", sen_t: "גדולים", sen_d: "עד גיל 10",
        sel_sub: "בחר נושא:", l_let: "אותיות", l_math: "חשבון",
        map: "מפת שלבים", dict: "מילון", hard: "קשה",
        p_let: "האות", p_num: "המספר", paint: "צייר!", pop: "פוצץ!",
        write: "כתוב מילה:", task: "תרגילים", table: "לוח הכפל", choose: "בחר מספר",
        yes: [
            "כל הכבוד!", "מצוין!", "סופר!", "נהדר!", "אתה חכם!",
            "יוצא לך מעולה!", "מדהים!", "פנטסטי!", "הצלחת!",
            "אתה כוכב!", "נפלא!", "אני גאה בך!",
            "אתה מעולה!", "תמשיך ככה!", "אתה משתפר!"
        ],
        no: [
            "נסה שוב, אתה יכול!", "כמעט! עוד פעם אחת!",
            "לא נורא, בוא ננסה שוב!", "הכל בסדר, בוא ננסה עוד!",
            "מאמץ טוב! נסה שוב!", "בפעם הבאה תצליח!",
            "אין בעיה! בוא ננסה ביחד!", "טעויות עוזרות ללמוד! נסה שוב!",
            "אל תוותר, אתה מסוגל!", "אני מאמין בך! נסה שוב!"
        ], find: "מצא מילים", find_p: "מצא:",
        select_lang: "בחר שפה:"
    }
};

// Database
const DB = {
    ru: {
        letters: [
            { l: 'А', t: 'А', s: 'А', ops: [{ w: 'Арбуз', i: '🍉' }, { w: 'Акула', i: '🦈' }, { w: 'Автобус', i: '🚌' }, { w: 'Апельсин', i: '🍊' }, { w: 'Ананас', i: '🍍' }] },
            { l: 'Б', t: 'Б', s: 'Бэ', ops: [{ w: 'Барабан', i: '🥁' }, { w: 'Банан', i: '🍌' }, { w: 'Белка', i: '🐿️' }, { w: 'Бабочка', i: '🦋' }, { w: 'Батон', i: '🥖' }] },
            { l: 'В', t: 'В', s: 'Вэ', ops: [{ w: 'Волк', i: '🐺' }, { w: 'Виноград', i: '🍇' }, { w: 'Велосипед', i: '🚲' }, { w: 'Вертолет', i: '🚁' }, { w: 'Вишня', i: '🍒' }] },
            { l: 'Г', t: 'Г', s: 'Гэ', ops: [{ w: 'Гриб', i: '🍄' }, { w: 'Гитара', i: '🎸' }, { w: 'Груша', i: '🍐' }, { w: 'Голубь', i: '🕊️' }, { w: 'Гора', i: '⛰️' }] },
            { l: 'Д', t: 'Д', s: 'Дэ', ops: [{ w: 'Дом', i: '🏠' }, { w: 'Дерево', i: '🌳' }, { w: 'Дельфин', i: '🐬' }, { w: 'Диван', i: '🛋️' }, { w: 'Дыня', i: '🍈' }] },
            { l: 'Е', t: 'Е', s: 'Е', ops: [{ w: 'Енот', i: '🦝' }, { w: 'Единорог', i: '🦄' }, { w: 'Ель', i: '🌲' }, { w: 'Ежевика', i: '🍇' }, { w: 'Еда', i: '🍲' }] },
            { l: 'Ё', t: 'Ё', s: 'Ё', ops: [{ w: 'Ёжик', i: '🦔' }, { w: 'Ёлка', i: '🎄' }, { w: 'Ёршик', i: '🖌️' }, { w: 'Ёрш', i: '🐟' }, { w: 'Ёлочная игрушка', i: '🎁' }] },
            { l: 'Ж', t: 'Ж', s: 'Жэ', ops: [{ w: 'Жираф', i: '🦒' }, { w: 'Жук', i: '🐞' }, { w: 'Жаба', i: '🐸' }, { w: 'Живот', i: '🌭' }, { w: 'Жемчуг', i: '💎' }] },
            { l: 'З', t: 'З', s: 'Зэ', ops: [{ w: 'Зебра', i: '🦓' }, { w: 'Заяц', i: '🐰' }, { w: 'Зонт', i: '☂️' }, { w: 'Замок', i: '🏰' }, { w: 'Змея', i: '🐍' }] },
            { l: 'И', t: 'И', s: 'И', ops: [{ w: 'Индюк', i: '🦃' }, { w: 'Игла', i: '💉' }, { w: 'Игрушка', i: '🧸' }, { w: 'Изба', i: '🛖' }, { w: 'Инопланетянин', i: '👽' }] },
            { l: 'Й', t: 'Й', s: 'Й краткое', ops: [{ w: 'Йог', i: '🧘' }, { w: 'Йогурт', i: '🍦' }, { w: 'Йод', i: '🧪' }, { w: 'Йоркшир', i: '🐕' }, { w: 'Йети', i: '🏔️' }] },
            { l: 'К', t: 'К', s: 'Ка', ops: [{ w: 'Кот', i: '🐈' }, { w: 'Корова', i: '🐄' }, { w: 'Кактус', i: '🌵' }, { w: 'Корона', i: '👑' }, { w: 'Ключ', i: '🔑' }] },
            { l: 'Л', t: 'Л', s: 'Эль', ops: [{ w: 'Лев', i: '🦁' }, { w: 'Лимон', i: '🍋' }, { w: 'Лиса', i: '🦊' }, { w: 'Лук', i: '🧅' }, { w: 'Лошадь', i: '🐴' }] },
            { l: 'М', t: 'М', s: 'Эм', ops: [{ w: 'Медведь', i: '🐻' }, { w: 'Машина', i: '🚗' }, { w: 'Мышь', i: '🐭' }, { w: 'Морковь', i: '🥕' }, { w: 'Молоко', i: '🥛' }] },
            { l: 'Н', t: 'Н', s: 'Эн', ops: [{ w: 'Носорог', i: '🦏' }, { w: 'Ножницы', i: '✂️' }, { w: 'Носок', i: '🧦' }, { w: 'Нитки', i: '🧵' }, { w: 'Нос', i: '👃' }] },
            { l: 'О', t: 'О', s: 'О', ops: [{ w: 'Обезьяна', i: '🐒' }, { w: 'Огурец', i: '🥒' }, { w: 'Орел', i: '🦅' }, { w: 'Очки', i: '👓' }, { w: 'Облако', i: '☁️' }] },
            { l: 'П', t: 'П', s: 'Пэ', ops: [{ w: 'Попугай', i: '🦜' }, { w: 'Паук', i: '🕷️' }, { w: 'Панда', i: '🐼' }, { w: 'Поезд', i: '🚂' }, { w: 'Помидор', i: '🍅' }] },
            { l: 'Р', t: 'Р', s: 'Эр', ops: [{ w: 'Рыба', i: '🐟' }, { w: 'Ракета', i: '🚀' }, { w: 'Радуга', i: '🌈' }, { w: 'Роза', i: '🌹' }, { w: 'Робот', i: '🤖' }] },
            { l: 'С', t: 'С', s: 'Эс', ops: [{ w: 'Слон', i: '🐘' }, { w: 'Собака', i: '🐕' }, { w: 'Солнце', i: '🌞' }, { w: 'Сыр', i: '🧀' }, { w: 'Сова', i: '🦉' }] },
            { l: 'Т', t: 'Т', s: 'Тэ', ops: [{ w: 'Тигр', i: '🐯' }, { w: 'Трактор', i: '🚜' }, { w: 'Торт', i: '🎂' }, { w: 'Тыква', i: '🎃' }, { w: 'Телефон', i: '📱' }] },
            { l: 'У', t: 'У', s: 'У', ops: [{ w: 'Утка', i: '🦆' }, { w: 'Улитка', i: '🐌' }, { w: 'Ухо', i: '👂' }, { w: 'Удочка', i: '🎣' }, { w: 'Уголь', i: '🌋' }] },
            { l: 'Ф', t: 'Ф', s: 'Эф', ops: [{ w: 'Фламинго', i: '🦩' }, { w: 'Фонарь', i: '🔦' }, { w: 'Фотоаппарат', i: '📸' }, { w: 'Фея', i: '🧚' }, { w: 'Футбол', i: '⚽' }] },
            { l: 'Х', t: 'Х', s: 'Ха', ops: [{ w: 'Хомяк', i: '🐹' }, { w: 'Хлеб', i: '🍞' }, { w: 'Холодильник', i: '❄️' }, { w: 'Хамелеон', i: '🦎' }, { w: 'Хот-дог', i: '🌭' }] },
            { l: 'Ц', t: 'Ц', s: 'Цэ', ops: [{ w: 'Цыпленок', i: '🐔' }, { w: 'Цветок', i: '🌸' }, { w: 'Царь', i: '🏰' }, { w: 'Цирк', i: '🎪' }, { w: 'Церковь', i: '⛪' }] },
            { l: 'Ч', t: 'Ч', s: 'Че', ops: [{ w: 'Черепаха', i: '🐢' }, { w: 'Чашка', i: '☕' }, { w: 'Часы', i: '⌚' }, { w: 'Чайник', i: '🍵' }, { w: 'Чемодан', i: '💼' }] },
            { l: 'Ш', t: 'Ш', s: 'Ша', ops: [{ w: 'Шар', i: '🎈' }, { w: 'Шоколад', i: '🍫' }, { w: 'Шарф', i: '🧣' }, { w: 'Шляпа', i: '🎩' }, { w: 'Шалаш', i: '⛺' }] },
            { l: 'Щ', t: 'Щ', s: 'Ща', ops: [{ w: 'Щетка', i: '🧹' }, { w: 'Щенок', i: '🐶' }, { w: 'Щит', i: '🛡️' }, { w: 'Щука', i: '🐟' }, { w: 'Щавель', i: '🥬' }] },
            { l: 'Ъ', t: 'Ъ', s: 'Твёрдый знак', ops: [{ w: 'Подъезд', i: '🚪' }, { w: 'Объявление', i: '📢' }, { w: 'Инъекция', i: '💉' }, { w: 'Съёмка', i: '🎥' }, { w: 'Съел', i: '🍽️' }] },
            { l: 'Ы', t: 'Ы', s: 'Ы', ops: [{ w: 'Сыр', i: '🧀' }, { w: 'Мышь', i: '🐭' }, { w: 'Дыня', i: '🍈' }, { w: 'Мыло', i: '🧼' }, { w: 'Рыба', i: '🐟' }] },
            { l: 'Ь', t: 'Ь', s: 'Мягкий знак', ops: [{ w: 'Олень', i: '🦌' }, { w: 'Лошадь', i: '🐎' }, { w: 'Соль', i: '🧂' }, { w: 'Картофель', i: '🥔' }, { w: 'Лебедь', i: '🦢' }] },
            { l: 'Э', t: 'Э', s: 'Э', ops: [{ w: 'Экскаватор', i: '🚜' }, { w: 'Эскимо', i: '🍦' }, { w: 'Электричество', i: '💡' }, { w: 'Экран', i: '📺' }, { w: 'Эверест', i: '🧗' }] },
            { l: 'Ю', t: 'Ю', s: 'Ю', ops: [{ w: 'Юла', i: '🌪️' }, { w: 'Юбка', i: '👗' }, { w: 'Юпитер', i: '🌌' }, { w: 'Юнга', i: '👦' }, { w: 'Юг', i: '🧭' }] },
            { l: 'Я', t: 'Я', s: 'Я', ops: [{ w: 'Яблоко', i: '🍎' }, { w: 'Ящерица', i: '🦎' }, { w: 'Яйцо', i: '🥚' }, { w: 'Якорь', i: '⚓' }, { w: 'Язык', i: '👅' }] }
        ],
        numbers: [
            { v: 1, t: 'Один', s: 'Один', w: 'Один', i: '🍎' },
            { v: 2, t: 'Два', s: 'Два', w: 'Два', i: '🍎🍎' },
            { v: 3, t: 'Три', s: 'Три', w: 'Три', i: '🍎🍎🍎' },
            { v: 4, t: 'Четыре', s: 'Четыре', w: 'Четыре', i: '🍎🍎🍎🍎' },
            { v: 5, t: 'Пять', s: 'Пять', w: 'Пять', i: '🍎🍎🍎🍎🍎' },
            { v: 6, t: 'Шесть', s: 'Шесть', w: 'Шесть', i: '🍎🍎🍎🍎🍎🍎' },
            { v: 7, t: 'Семь', s: 'Семь', w: 'Семь', i: '🍎🍎🍎🍎🍎🍎🍎' },
            { v: 8, t: 'Восемь', s: 'Восемь', w: 'Восемь', i: '🍎🍎🍎🍎🍎🍎🍎🍎' },
            { v: 9, t: 'Девять', s: 'Девять', w: 'Девять', i: '🍎🍎🍎🍎🍎🍎🍎🍎🍎' },
            { v: 10, t: 'Десять', s: 'Десять', w: 'Десять', i: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎' }
        ],
        syllableWords: [
            { word: 'ба-то́н', syllables: ['ба', 'то́н'], stressIndex: 1, emoji: '🥖' },
            { word: 'ба-на́н', syllables: ['ба', 'на́н'], stressIndex: 1, emoji: '🍌' },
            { word: 'ба́н-ка', syllables: ['ба́н', 'ка'], stressIndex: 0, emoji: '🏺' },
            { word: 'ка-ба́н', syllables: ['ка', 'ба́н'], stressIndex: 1, emoji: '🐗' },
            { word: 'со-ба́-ка', syllables: ['со', 'ба́', 'ка'], stressIndex: 1, emoji: '🐕' },
            { word: 'о́к-но', syllables: ['о́к', 'но'], stressIndex: 0, emoji: '🪟' },
            { word: 'ко́-ты', syllables: ['ко́', 'ты'], stressIndex: 0, emoji: '🐈' },
            { word: 'пу-шо́к', syllables: ['пу', 'шо́к'], stressIndex: 1, emoji: '🐾' },
            { word: 'ку-со́к', syllables: ['ку', 'со́к'], stressIndex: 1, emoji: '🍰' },
            { word: 'мы́ш-ка', syllables: ['мы́ш', 'ка'], stressIndex: 0, emoji: '🐭' },
            { word: 'ма́с-ка', syllables: ['ма́с', 'ка'], stressIndex: 0, emoji: '🎭' },
            { word: 'ка́ш-ка', syllables: ['ка́ш', 'ка'], stressIndex: 0, emoji: '🥣' },
            { word: 'ка́с-ка', syllables: ['ка́с', 'ка'], stressIndex: 0, emoji: '⛑️' },
            { word: 'шу́т-ка', syllables: ['шу́т', 'ка'], stressIndex: 0, emoji: '😄' },
            { word: 'ко-ле-со́', syllables: ['ко', 'ле', 'со́'], stressIndex: 2, emoji: '🎡' },
            { word: 'пу́ш-ка', syllables: ['пу́ш', 'ка'], stressIndex: 0, emoji: '💣' },
            { word: 'ме́-сто', syllables: ['ме́с', 'то'], stressIndex: 0, emoji: '📍' },
            { word: 'ке́п-ка', syllables: ['ке́п', 'ка'], stressIndex: 0, emoji: '🧢' },
            { word: 'бе́л-ка', syllables: ['бе́л', 'ка'], stressIndex: 0, emoji: '🐿️' },
            { word: 'ша́п-ка', syllables: ['ша́п', 'ка'], stressIndex: 0, emoji: '🧶' },
            { word: 'ка-ту́ш-ка', syllables: ['ка', 'ту́ш', 'ка'], stressIndex: 1, emoji: '🧵' },
            { word: 'ма-ку́ш-ка', syllables: ['ма', 'ку́ш', 'ка'], stressIndex: 1, emoji: '👤' },
            { word: 'ко́ш-ка', syllables: ['ко́ш', 'ка'], stressIndex: 0, emoji: '🐱' },
            { word: 'ма-ту́ш-ка', syllables: ['ма', 'ту́ш', 'ка'], stressIndex: 1, emoji: '👵' },
            { word: 'стре́л-ка', syllables: ['стре́л', 'ка'], stressIndex: 0, emoji: '➡️' },
            { word: 'лу-на́', syllables: ['лу', 'на́'], stressIndex: 1, emoji: '🌙' },
            { word: 'пы́ш-ка', syllables: ['пы́ш', 'ка'], stressIndex: 0, emoji: '🍩' },
            { word: 'бу́л-ка', syllables: ['бу́л', 'ка'], stressIndex: 0, emoji: '🍞' }
        ],
        locale: 'ru-RU'
    },
    en: {
        letters: [
            { l: 'A', t: 'A', s: 'A', ops: [{ w: 'Apple', i: '🍎' }, { w: 'Ant', i: '🐜' }, { w: 'Airplane', i: '✈️' }, { w: 'Alligator', i: '🐊' }, { w: 'Arrow', i: '🏹' }] },
            { l: 'B', t: 'B', s: 'B', ops: [{ w: 'Banana', i: '🍌' }, { w: 'Bear', i: '🐻' }, { w: 'Ball', i: '⚽' }, { w: 'Butterfly', i: '🦋' }, { w: 'Bus', i: '🚌' }] },
            { l: 'C', t: 'C', s: 'C', ops: [{ w: 'Cat', i: '🐈' }, { w: 'Car', i: '🚗' }, { w: 'Cake', i: '🍰' }, { w: 'Cow', i: '🐄' }, { w: 'Carrot', i: '🥕' }] },
            { l: 'D', t: 'D', s: 'D', ops: [{ w: 'Dog', i: '🐕' }, { w: 'Duck', i: '🦆' }, { w: 'Drum', i: '🥁' }, { w: 'Door', i: '🚪' }, { w: 'Dolphin', i: '🐬' }] },
            { l: 'E', t: 'E', s: 'E', ops: [{ w: 'Elephant', i: '🐘' }, { w: 'Egg', i: '🥚' }, { w: 'Eagle', i: '🦅' }, { w: 'Ear', i: '👂' }, { w: 'Eye', i: '👀' }] },
            { l: 'F', t: 'F', s: 'F', ops: [{ w: 'Fish', i: '🐟' }, { w: 'Fox', i: '🦊' }, { w: 'Frog', i: '🐸' }, { w: 'Flower', i: '🌸' }, { w: 'Fire', i: '🔥' }] },
            { l: 'G', t: 'G', s: 'G', ops: [{ w: 'Giraffe', i: '🦒' }, { w: 'Grapes', i: '🍇' }, { w: 'Goat', i: '🐐' }, { w: 'Gift', i: '🎁' }, { w: 'Guitar', i: '🎸' }] },
            { l: 'H', t: 'H', s: 'H', ops: [{ w: 'House', i: '🏠' }, { w: 'Horse', i: '🐴' }, { w: 'Hat', i: '🎩' }, { w: 'Helicopter', i: '🚁' }, { w: 'Hamster', i: '🐹' }] },
            { l: 'I', t: 'I', s: 'I', ops: [{ w: 'Ice Cream', i: '🍦' }, { w: 'Iguana', i: '🦎' }, { w: 'Ice', i: '🧊' }, { w: 'Island', i: '🏝️' }, { w: 'Insect', i: '🐜' }] },
            { l: 'J', t: 'J', s: 'J', ops: [{ w: 'Jellyfish', i: '🎐' }, { w: 'Jeans', i: '👖' }, { w: 'Juice', i: '🧃' }, { w: 'Jaguar', i: '🐆' }, { w: 'Jet', i: '🚁' }] },
            { l: 'K', t: 'K', s: 'K', ops: [{ w: 'Kangaroo', i: '🦘' }, { w: 'Key', i: '🔑' }, { w: 'Kite', i: '🪁' }, { w: 'Kiwi', i: '🥝' }, { w: 'King', i: '👑' }] },
            { l: 'L', t: 'L', s: 'L', ops: [{ w: 'Lion', i: '🦁' }, { w: 'Lemon', i: '🍋' }, { w: 'Leaf', i: '🍃' }, { w: 'Ladybug', i: '🐞' }, { w: 'Lamp', i: '💡' }] },
            { l: 'M', t: 'M', s: 'M', ops: [{ w: 'Monkey', i: '🐒' }, { w: 'Moon', i: '🌙' }, { w: 'Mouse', i: '🐭' }, { w: 'Milk', i: '🥛' }, { w: 'Map', i: '🗺️' }] },
            { l: 'N', t: 'N', s: 'N', ops: [{ w: 'Nose', i: '👃' }, { w: 'Nut', i: '🥜' }, { w: 'Net', i: '🕸️' }, { w: 'Night', i: '🦉' }, { w: 'Nest', i: '🪹' }] },
            { l: 'O', t: 'O', s: 'O', ops: [{ w: 'Octopus', i: '🐙' }, { w: 'Orange', i: '🍊' }, { w: 'Owl', i: '🦉' }, { w: 'Onion', i: '🧅' }, { w: 'Ocean', i: '🌊' }] },
            { l: 'P', t: 'P', s: 'P', ops: [{ w: 'Penguin', i: '🐧' }, { w: 'Pizza', i: '🍕' }, { w: 'Panda', i: '🐼' }, { w: 'Parrot', i: '🦜' }, { w: 'Pear', i: '🍐' }] },
            { l: 'Q', t: 'Q', s: 'Q', ops: [{ w: 'Queen', i: '👸' }, { w: 'Question', i: '❓' }, { w: 'Quack', i: '🦆' }, { w: 'Quiet', i: '🤫' }, { w: 'Quilt', i: '🛌' }] },
            { l: 'R', t: 'R', s: 'R', ops: [{ w: 'Rabbit', i: '🐰' }, { w: 'Robot', i: '🤖' }, { w: 'Rocket', i: '🚀' }, { w: 'Rose', i: '🌹' }, { w: 'Ring', i: '💍' }] },
            { l: 'S', t: 'S', s: 'S', ops: [{ w: 'Snake', i: '🐍' }, { w: 'Sun', i: '🌞' }, { w: 'Star', i: '⭐' }, { w: 'Spider', i: '🕷️' }, { w: 'Sandwich', i: '🥪' }] },
            { l: 'T', t: 'T', s: 'T', ops: [{ w: 'Tiger', i: '🐯' }, { w: 'Tree', i: '🌲' }, { w: 'Turtle', i: '🐢' }, { w: 'Train', i: '🚂' }, { w: 'Tomato', i: '🍅' }] },
            { l: 'U', t: 'U', s: 'U', ops: [{ w: 'Unicorn', i: '🦄' }, { w: 'Umbrella', i: '☂️' }, { w: 'Up', i: '🆙' }, { w: 'UFO', i: '🛸' }, { w: 'Unicycle', i: '🚲' }] },
            { l: 'V', t: 'V', s: 'V', ops: [{ w: 'Violin', i: '🎻' }, { w: 'Volcano', i: '🌋' }, { w: 'Van', i: '🚐' }, { w: 'Vegetable', i: '🥦' }, { w: 'Volleyball', i: '🏐' }] },
            { l: 'W', t: 'W', s: 'W', ops: [{ w: 'Whale', i: '🐋' }, { w: 'Watermelon', i: '🍉' }, { w: 'Wolf', i: '🐺' }, { w: 'Watch', i: '⌚' }, { w: 'Web', i: '🕸️' }] },
            { l: 'X', t: 'X', s: 'X', ops: [{ w: 'Xylophone', i: '🎄' }, { w: 'Box', i: '📦' }, { w: 'Fox', i: '🦊' }, { w: 'X-ray', i: '❌' }, { w: 'Wax', i: '🕯️' }] },
            { l: 'Y', t: 'Y', s: 'Y', ops: [{ w: 'Yacht', i: '🛥️' }, { w: 'Yarn', i: '🧶' }, { w: 'Yoga', i: '🧘' }, { w: 'Yellow', i: '🟡' }, { w: 'Yo-yo', i: '🪀' }] },
            { l: 'Z', t: 'Z', s: 'Z', ops: [{ w: 'Zebra', i: '🦓' }, { w: 'Zipper', i: '🤐' }, { w: 'Zombie', i: '🧟' }, { w: 'Zucchini', i: '🥒' }, { w: 'Zap', i: '⚡' }] }
        ],
        numbers: [
            { v: 1, t: 'One', s: 'One', w: 'One', i: '🍎' },
            { v: 2, t: 'Two', s: 'Two', w: 'Two', i: '🍎🍎' },
            { v: 3, t: 'Three', s: 'Three', w: 'Three', i: '🍎🍎🍎' },
            { v: 4, t: 'Four', s: 'Four', w: 'Four', i: '🍎🍎🍎🍎' },
            { v: 5, t: 'Five', s: 'Five', w: 'Five', i: '🍎🍎🍎🍎🍎' },
            { v: 6, t: 'Six', s: 'Six', w: 'Six', i: '🍎🍎🍎🍎🍎🍎' },
            { v: 7, t: 'Seven', s: 'Seven', w: 'Seven', i: '🍎🍎🍎🍎🍎🍎🍎' },
            { v: 8, t: 'Eight', s: 'Eight', w: 'Eight', i: '🍎🍎🍎🍎🍎🍎🍎🍎' },
            { v: 9, t: 'Nine', s: 'Nine', w: 'Nine', i: '🍎🍎🍎🍎🍎🍎🍎🍎🍎' },
            { v: 10, t: 'Ten', s: 'Ten', w: 'Ten', i: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎' }
        ],
        syllableWords: [
            { word: 'ba-con', syllables: ['ba', 'con'], stressIndex: 0, emoji: '🥓' },
            { word: 'ba-na-na', syllables: ['ba', 'na', 'na'], stressIndex: 1, emoji: '🍌' },
            { word: 'bot-tle', syllables: ['bot', 'tle'], stressIndex: 0, emoji: '🍼' },
            { word: 'ti-ger', syllables: ['ti', 'ger'], stressIndex: 0, emoji: '🐅' },
            { word: 'pup-py', syllables: ['pup', 'py'], stressIndex: 0, emoji: '🐶' },
            { word: 'win-dow', syllables: ['win', 'dow'], stressIndex: 0, emoji: '🪟' },
            { word: 'kit-ty', syllables: ['kit', 'ty'], stressIndex: 0, emoji: '🐈' },
            { word: 'cook-ie', syllables: ['cook', 'ie'], stressIndex: 0, emoji: '🍪' },
            { word: 'ap-ple', syllables: ['ap', 'ple'], stressIndex: 0, emoji: '🍎' },
            { word: 'mous-ie', syllables: ['mous', 'ie'], stressIndex: 0, emoji: '🐭' },
            { word: 'pen-cil', syllables: ['pen', 'cil'], stressIndex: 0, emoji: '✏️' },
            { word: 'ta-ble', syllables: ['ta', 'ble'], stressIndex: 0, emoji: '📋' },
            { word: 'hel-met', syllables: ['hel', 'met'], stressIndex: 0, emoji: '⛑️' },
            { word: 'fun-ny', syllables: ['fun', 'ny'], stressIndex: 0, emoji: '😄' },
            { word: 'cir-cle', syllables: ['cir', 'cle'], stressIndex: 0, emoji: '⭕' },
            { word: 'can-non', syllables: ['can', 'non'], stressIndex: 0, emoji: '💣' },
            { word: 'pock-et', syllables: ['pock', 'et'], stressIndex: 0, emoji: '👝' },
            { word: 'bas-ket', syllables: ['bas', 'ket'], stressIndex: 0, emoji: '🧺' },
            { word: 'squir-rel', syllables: ['squir', 'rel'], stressIndex: 0, emoji: '🐿️' },
            { word: 'mit-ten', syllables: ['mit', 'ten'], stressIndex: 0, emoji: '🧤' },
            { word: 'but-ton', syllables: ['but', 'ton'], stressIndex: 0, emoji: '🔘' },
            { word: 'ar-row', syllables: ['ar', 'row'], stressIndex: 0, emoji: '➡️' },
            { word: 'moon', syllables: ['moon'], stressIndex: 0, emoji: '🌙' },
            { word: 'do-nut', syllables: ['do', 'nut'], stressIndex: 0, emoji: '🍩' },
            { word: 'bread', syllables: ['bread'], stressIndex: 0, emoji: '🍞' }
        ],
        locale: 'en-US'
    },
    he: {
        letters: [
            { l: 'א', t: 'א', s: 'אָלֶף', ops: [{ w: 'אריה', i: '🦁' }, { w: 'אבטיח', i: '🍉' }, { w: 'אבוקדו', i: '🥑' }, { w: 'אופניים', i: '🚲' }, { w: 'אבא', i: '👨' }] },
            { l: 'ב', t: 'ב', s: 'בֵּית', ops: [{ w: 'בית', i: '🏠' }, { w: 'בננה', i: '🍌' }, { w: 'בלון', i: '🎈' }, { w: 'ברווז', i: '🦆' }, { w: 'בצל', i: '🧅' }] },
            { l: 'ג', t: 'ג', s: 'גִּימֶל', ops: [{ w: 'גמל', i: '🐫' }, { w: 'גזר', i: '🥕' }, { w: 'ג׳ירפה', i: '🦒' }, { w: 'גלידה', i: '🍦' }, { w: 'גבינה', i: '🧀' }] },
            { l: 'ד', t: 'ד', s: 'דָּלֶת', ops: [{ w: 'דלת', i: '🚪' }, { w: 'דג', i: '🐟' }, { w: 'דוב', i: '🐼' }, { w: 'דקל', i: '🌴' }, { w: 'דולפין', i: '🐬' }] },
            { l: 'ה', t: 'ה', s: 'הֵא', ops: [{ w: 'הר', i: '🏔️' }, { w: 'היפופוטם', i: '🦛' }, { w: 'הפתעה', i: '🎁' }, { w: 'הליקופטר', i: '🚁' }, { w: 'הודו', i: '🦃' }] },
            { l: 'ו', t: 'ו', s: 'וָו', ops: [{ w: 'ורד', i: '🌹' }, { w: 'ויולה', i: '🎻' }, { w: 'וופל', i: '🧇' }, { w: 'וואן', i: '🚐' }, { w: 'הר געש', i: '🌋' }] },
            { l: 'ז', t: 'ז', s: 'זַיִן', ops: [{ w: 'זברה', i: '🦓' }, { w: 'זית', i: '🫒' }, { w: 'זאב', i: '🐺' }, { w: 'זבוב', i: '🪰' }, { w: 'זיקית', i: '🦎' }] },
            { l: 'ח', t: 'ח', s: 'חֵית', ops: [{ w: 'חתול', i: '🐈' }, { w: 'חלב', i: '🥛' }, { w: 'חילזון', i: '🐌' }, { w: 'חמאה', i: '🧈' }, { w: 'חולצה', i: '👚' }] },
            { l: 'ט', t: 'ט', s: 'טֵית', ops: [{ w: 'טרקטור', i: '🚜' }, { w: 'טבעת', i: '💍' }, { w: 'טלוויזיה', i: '📺' }, { w: 'טניס', i: '🎾' }, { w: 'טיגריס', i: '🐅' }] },
            { l: 'י', t: 'י', s: 'יוֹד', ops: [{ w: 'ינשוף', i: '🦉' }, { w: 'ירח', i: '🌙' }, { w: 'ילד', i: '👦' }, { w: 'ילדה', i: '👧' }, { w: 'ים', i: '🌊' }] },
            { l: 'כ', t: 'כ', s: 'כַּף', ops: [{ w: 'כלב', i: '🐕' }, { w: 'כדור', i: '⚽' }, { w: 'כף', i: '🥄' }, { w: 'כבשה', i: '🐑' }, { w: 'כובע', i: '🧢' }] },
            { l: 'ל', t: 'ל', s: 'לָמֶד', ops: [{ w: 'לימון', i: '🍋' }, { w: 'לחם', i: '🥖' }, { w: 'לוויתן', i: '🐋' }, { w: 'לטאה', i: '🦎' }, { w: 'לפיד', i: '🔦' }] },
            { l: 'מ', t: 'מ', s: 'מֵם', ops: [{ w: 'מכונית', i: '🚗' }, { w: 'מלפפון', i: '🥒' }, { w: 'מפתח', i: '🗝️' }, { w: 'מטוס', i: '✈️' }, { w: 'ממתק', i: '🍬' }] },
            { l: 'נ', t: 'נ', s: 'נוּן', ops: [{ w: 'נחש', i: '🐍' }, { w: 'נמלה', i: '🐜' }, { w: 'נר', i: '🕯️' }, { w: 'נמר', i: '🐆' }, { w: 'נעליים', i: '👟' }] },
            { l: 'ס', t: 'ס', s: 'סָמֶךְ', ops: [{ w: 'סוס', i: '🐴' }, { w: 'ספר', i: '📚' }, { w: 'סירה', i: '🚢' }, { w: 'סולם', i: '🪜' }, { w: 'סוכריה', i: '🍬' }] },
            { l: 'ע', t: 'ע', s: 'עַיִן', ops: [{ w: 'עוגה', i: '🎂' }, { w: 'ענבים', i: '🍇' }, { w: 'עגבניה', i: '🍅' }, { w: 'עטלף', i: '🦇' }, { w: 'עט', i: '🖊️' }] },
            { l: 'פ', t: 'פ', s: 'פֵּא', ops: [{ w: 'פיל', i: '🐘' }, { w: 'פרפר', i: '🦋' }, { w: 'פסנתר', i: '🎹' }, { w: 'פטריה', i: '🍄' }, { w: 'פסטה', i: '🍝' }] },
            { l: 'צ', t: 'צ', s: 'צַדִּי', ops: [{ w: 'צב', i: '🐢' }, { w: 'צפרדע', i: '🐸' }, { w: 'צלחת', i: '🍽️' }, { w: 'צבי', i: '🦌' }, { w: 'צבע', i: '🎨' }] },
            { l: 'ק', t: 'ק', s: 'קוֹף', ops: [{ w: 'קוף', i: '🐒' }, { w: 'קיווי', i: '🥝' }, { w: 'קטר', i: '🚂' }, { w: 'קקטוס', i: '🌵' }, { w: 'קערה', i: '🥣' }] },
            { l: 'ר', t: 'ר', s: 'רֵישׁ', ops: [{ w: 'רכבת', i: '🚂' }, { w: 'רדיו', i: '📻' }, { w: 'רגל', i: '🦶' }, { w: 'רמזור', i: '🚦' }, { w: 'רהיט', i: '🛋️' }] },
            { l: 'ש', t: 'ש', s: 'שִׁין', ops: [{ w: 'שמש', i: '🌞' }, { w: 'שעון', i: '⌚' }, { w: 'שבלול', i: '🐌' }, { w: 'שוקולד', i: '🍫' }, { w: 'שן', i: '🦷' }] },
            { l: 'ת', t: 'ת', s: 'תָּו', ops: [{ w: 'תות', i: '🍓' }, { w: 'תנין', i: '🐊' }, { w: 'תרנגול', i: '🐔' }, { w: 'תיק', i: '🎒' }, { w: 'תירס', i: '🌽' }] }
        ],
        numbers: [
            { v: 1, t: 'אחת', s: 'אַחַת', w: 'אחת', i: '🍎' },
            { v: 2, t: 'שתיים', s: 'שְׁתַּיִם', w: 'שתיים', i: '🍎🍎' },
            { v: 3, t: 'שלוש', s: 'שָׁלוֹשׁ', w: 'שלוש', i: '🍎🍎🍎' },
            { v: 4, t: 'ארבע', s: 'אַרְבַּע', w: 'ארבע', i: '🍎🍎🍎🍎' },
            { v: 5, t: 'חמש', s: 'חָמֵשׁ', w: 'חמש', i: '🍎🍎🍎🍎🍎' },
            { v: 6, t: 'שש', s: 'שֵׁשׁ', w: 'שש', i: '🍎🍎🍎🍎🍎🍎' },
            { v: 7, t: 'שבע', s: 'שֶׁבַע', w: 'שבע', i: '🍎🍎🍎🍎🍎🍎🍎' },
            { v: 8, t: 'שמונה', s: 'שְׁמוֹנֶה', w: 'שמונה', i: '🍎🍎🍎🍎🍎🍎🍎🍎' },
            { v: 9, t: 'תשע', s: 'תֵּשַׁע', w: 'תשע', i: '🍎🍎🍎🍎🍎🍎🍎🍎🍎' },
            { v: 10, t: 'עשר', s: 'עֶשֶׂר', w: 'עשר', i: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎' }
        ],
        syllableWords: [
            { word: 'לֶ-חֶם', syllables: ['לֶ', 'חֶם'], stressIndex: 0, emoji: '🍞' },
            { word: 'בָּ-נָ-נָה', syllables: ['בָּ', 'נָ', 'נָה'], stressIndex: 1, emoji: '🍌' },
            { word: 'בַּ-קְ-בּוּק', syllables: ['בַּ', 'קְ', 'בּוּק'], stressIndex: 2, emoji: '🍼' },
            { word: 'חָ-זִיר', syllables: ['חָ', 'זִיר'], stressIndex: 1, emoji: '🐗' },
            { word: 'כֶּ-לֶב', syllables: ['כֶּ', 'לֶב'], stressIndex: 1, emoji: '🐕' },
            { word: 'חַ-לּוֹן', syllables: ['חַ', 'לּוֹן'], stressIndex: 1, emoji: '🪟' },
            { word: 'חָ-תוּל', syllables: ['חָ', 'תוּל'], stressIndex: 1, emoji: '🐈' },
            { word: 'עוּ-גָה', syllables: ['עוּ', 'גָה'], stressIndex: 1, emoji: '🍰' },
            { word: 'עַ-כְ-בָּר', syllables: ['עַ', 'כְ', 'בָּר'], stressIndex: 2, emoji: '🐭' },
            { word: 'מַ-סֵּ-כָה', syllables: ['מַ', 'סֵּ', 'כָה'], stressIndex: 2, emoji: '🎭' },
            { word: 'דַּ-יָּה', syllables: ['דַּ', 'יָּה'], stressIndex: 1, emoji: '🥣' },
            { word: 'כּוֹ-בַע', syllables: ['כּוֹ', 'בַע'], stressIndex: 1, emoji: '⛑️' },
            { word: 'בְּ-דִי-חָה', syllables: ['בְּ', 'דִי', 'חָה'], stressIndex: 2, emoji: '😄' },
            { word: 'גַּל-גַּל', syllables: ['גַּל', 'גַּל'], stressIndex: 1, emoji: '🎡' },
            { word: 'תּוֹ-תָח', syllables: ['תּוֹ', 'תָח'], stressIndex: 1, emoji: '💣' },
            { word: 'מָ-קוֹם', syllables: ['מָ', 'קוֹם'], stressIndex: 1, emoji: '📍' },
            { word: 'כּוֹ-בַע', syllables: ['כּוֹ', 'בַע'], stressIndex: 1, emoji: '🧢' },
            { word: 'סְ-נַאי', syllables: ['סְ', 'נַאי'], stressIndex: 1, emoji: '🐿️' },
            { word: 'כּוֹ-בַע', syllables: ['כּוֹ', 'בַע'], stressIndex: 1, emoji: '🧶' },
            { word: 'חָ-תוּל', syllables: ['חָ', 'תוּל'], stressIndex: 1, emoji: '🐱' },
            { word: 'חֵץ', syllables: ['חֵץ'], stressIndex: 0, emoji: '➡️' },
            { word: 'יָ-רֵ-חַ', syllables: ['יָ', 'רֵ', 'חַ'], stressIndex: 1, emoji: '🌙' },
            { word: 'סֻ-פְ-גָּנִיָּה', syllables: ['סֻ', 'פְ', 'גָּנִיָּה'], stressIndex: 2, emoji: '🍩' },
            { word: 'לֶ-חֶם', syllables: ['לֶ', 'חֶם'], stressIndex: 1, emoji: '🍞' }
        ],
        locale: 'he-IL'
    }
};
